language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7'
    - hhvm
    - nightly
script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --debug --verbose --coverage-clover build/logs/clover.xml t/Test
before_install:
    - composer install --dev
after_script:
    - php vendor/bin/coveralls -v
